const { Router } = require('express')
const { getHomePage } = require('./home')
const { query1, query2, query3, query4, query40, query5, query6, query7, query8, query9, query10 } = require('./queries')
const { searchPlayers, searchTeams, response1, response2, response3, response4, response40, response5, response6, response7, response8, response9, response10 } = require("./responses")
const homeRouter = new Router()
const queryRouter = new Router()
const responseRouter = new Router()
homeRouter.get('/', getHomePage)
queryRouter.get('/1', query1)
// queryRouter.get('/2', query2)
// queryRouter.get('/3', query3)
queryRouter.get('/4', query4)
queryRouter.get('/40', query40)
queryRouter.get('/5', query5)
queryRouter.get('/6', query6)
queryRouter.get('/7', query7)
queryRouter.get('/8', query8)
queryRouter.get('/9', query9)
queryRouter.get('/10', query10)
responseRouter.get('/search', searchPlayers)
responseRouter.get('/searchTeam', searchTeams)
responseRouter.post('/1', response1)
// responseRouter.get('/2', response2)
// responseRouter.get('/3', response3)
responseRouter.post('/4', response4)
responseRouter.post('/40', response40)
responseRouter.get('/5', response5)
responseRouter.get('/6', response6)
responseRouter.post('/7', response7)
responseRouter.post('/8', response8)
responseRouter.post('/9', response9)
responseRouter.post('/10', response10)
module.exports = {homeRouter, queryRouter, responseRouter}
